/* Marisa "I shouldn't be let anywhere near ZScript" Kirisame */
Class mkMarisa : Actor
{
	void A_MarisaSpecial()
	{
		// Nothing here yet
	}

	override void Activate( Actor activator )
	{
		SetStateLabel("Magic");
	}

	Default
	{
		//$Title "Marisa Kirisame"
		//$Category "Marisa Kirisame"
		Radius 15;
		Height 50;
		Scale 0.35;
		+NOGRAVITY
		+SOLID
	}

	States
	{
	Spawn:
		MARI ABCDEFGHIJKLMNO 3;
		Loop;
	Magic:
		MARI PQR 3;
		MARI S 3 A_MarisaSpecial;
		MARI TUVWXY 3;
		Goto Spawn;
	}
}
